version: '3.9'

services:
  postgres:
    image: postgres:16
    container_name: marketflow-postgres
    restart: always
    env_file: .env
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "${POSTGRES_PORT}:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql:ro

  redis:
    image: redis:7
    container_name: marketflow-redis
    restart: always
    ports:
      - "${REDIS_PORT}:6379"

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: marketflow-app
    env_file: .env
    depends_on:
      - postgres
      - redis
    ports:
      - "${SERVER_PORT}:8080"

volumes:
  postgres_data:
